project:
  type: website

website:
  site-url: https://statml.berkeley.edu
  title: "Berkeley StatML"
  sidebar:
    style: docked
    logo: assets/logo/logo.png
    logo-alt: "Logo"
    background: "#f9f9f9"
    contents:
      - href: index.qmd
        text: Home
      - href: index.qmd#news
        text: News
      - href: index.qmd#faculty
        text: Faculty
      - href: index.qmd#postdocs
        text: Postdocs
      - href: index.qmd#students
        text: Students
      # - href: index.qmd#alumni
      #   text: Alumni

format:
  html:
    theme: cosmo
    css: assets/styles.css
    toc: false # true
